#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-truncnorm
Version  : 1.0.8
Release  : 13
URL      : https://cran.r-project.org/src/contrib/truncnorm_1.0-8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/truncnorm_1.0-8.tar.gz
Summary  : Truncated Normal Distribution
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-truncnorm-lib
BuildRequires : clr-R-helpers

%description
generation functions for the truncated normal distribution.

%package lib
Summary: lib components for the R-truncnorm package.
Group: Libraries

%description lib
lib components for the R-truncnorm package.


%prep
%setup -q -c -n truncnorm

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521226639

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1521226639
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library truncnorm
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library truncnorm
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library truncnorm
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library truncnorm|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/truncnorm/DESCRIPTION
/usr/lib64/R/library/truncnorm/INDEX
/usr/lib64/R/library/truncnorm/Meta/Rd.rds
/usr/lib64/R/library/truncnorm/Meta/features.rds
/usr/lib64/R/library/truncnorm/Meta/hsearch.rds
/usr/lib64/R/library/truncnorm/Meta/links.rds
/usr/lib64/R/library/truncnorm/Meta/nsInfo.rds
/usr/lib64/R/library/truncnorm/Meta/package.rds
/usr/lib64/R/library/truncnorm/NAMESPACE
/usr/lib64/R/library/truncnorm/R/truncnorm
/usr/lib64/R/library/truncnorm/R/truncnorm.rdb
/usr/lib64/R/library/truncnorm/R/truncnorm.rdx
/usr/lib64/R/library/truncnorm/help/AnIndex
/usr/lib64/R/library/truncnorm/help/aliases.rds
/usr/lib64/R/library/truncnorm/help/paths.rds
/usr/lib64/R/library/truncnorm/help/truncnorm.rdb
/usr/lib64/R/library/truncnorm/help/truncnorm.rdx
/usr/lib64/R/library/truncnorm/html/00Index.html
/usr/lib64/R/library/truncnorm/html/R.css
/usr/lib64/R/library/truncnorm/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/truncnorm/libs/truncnorm.so
/usr/lib64/R/library/truncnorm/libs/truncnorm.so.avx2
/usr/lib64/R/library/truncnorm/libs/truncnorm.so.avx512
